"""empty message

Revision ID: 4d8c1961d9c1
Revises: 12a2fb78ec1b
Create Date: 2021-04-07 06:32:37.639734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8c1961d9c1'
down_revision = '12a2fb78ec1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('character', sa.Column('favorite_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'character', 'favorite', ['favorite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'character', type_='foreignkey')
    op.drop_column('character', 'favorite_id')
    op.drop_table('favorite')
    # ### end Alembic commands ###
